version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin@123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql/data
      - sqlserver_backup:/var/opt/mssql/backup
      - sqlserver_log:/var/opt/mssql/log
    restart: unless-stopped

volumes:
  sqlserver_data:
  sqlserver_backup:
  sqlserver_log: